
save_data: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/training/data
## Where the vocab(s) will be written
src_vocab: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/vocab/vocab.src 
tgt_vocab: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/vocab/vocab.src 
share_vocab: true

train_from: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/training/model/model_step_155000.pt

data:
    Mizo_wmt:
        path_src: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/bpe_codes/wmt/train.bpe.en
        path_tgt: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/bpe_codes/wmt/train.bpe.lus
        weight: 1.1
        transforms: [filtertoolong]
    valid:
        path_src: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/bpe_codes/wmt/valid.bpe.en
        path_tgt: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/bpe_codes/wmt/valid.bpe.lus
        transforms: [filtertoolong]

#### Filter
src_seq_length: 512
tgt_seq_length: 512
src_seq_length_trunc: 512   
tgt_seq_length_trunc: 512
src_vocab_size: 48000
tgt_vocab_size: 48000
src_subword_type: none
tgt_subword_type: none
vocab_sample_size: -1
skip_empty_level: silent
reset_optim: all

# Train on a single GPU
world_size: 4
gpu_ranks: [0, 1, 2, 3]
timeout: 3600

log_file: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/training/logs/mizo_finetune_only_wmt.log

# General opts
save_model: /nlsasfs/home/bhasngrh/vedhe/WMT2026/Indic-LR/En-Lus/training/model_finetune_wmt/model
keep_checkpoint: 10
save_checkpoint_steps: 3000 #50000

seed: 1234
report_every: 500 #5000
train_steps: 200000
valid_steps: 3000


# Batching
queue_size: 8000 
bucket_size: 65536 
num_workers: 8       
prefetch_factor: 4    

batch_type: "tokens"
batch_size: 2048 
valid_batch_size: 512 
batch_size_multiple: 8
vocab_size_multiple: 8
max_generator_batches: 0
accum_count: [4] 
adam_beta1: 0.9
adam_beta2: 0.998


# Early Stopping
early_stopping: 5
early_stopping_criteria: ppl 

# Optimization
apex_opt_level: "" 
precision: bf16 
optim: "adam"
learning_rate: 0.0002 
warmup_steps: 100
hidden_size: 512       
embedding_dim: 512    
decay_method: "none" 
max_grad_norm: 1.0
label_smoothing: 0.1
param_init: 0
param_init_glorot: 'true'
position_encoding: 'true'
normalization: "tokens"
self_attn_type: "scaled-dot"  
pos_ffn_activation_fn: "gelu"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512 #-1
transformer_ff: 2048
dropout: [0.1]
attention_dropout: [0.1]
tensorboard: true
tensorboard_log_dir: "runs/"